name: rosmap
version: git
summary: rosmap
description: Clones and analyzes ROS-Packages.

confinement: devmode

parts:
  git:
    plugin: autotools
    build-packages:
      - dh-autoreconf
      - libcurl4-gnutls-dev
      - libexpat1-dev
      - gettext
      - libz-dev
      - libssl-dev
    source: https://github.com/git/git/archive/v2.15.1.tar.gz
  rosmap:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - mercurial
      - subversion

apps:
  rosmap:
    command: bin/rosmap_launcher.py
    plugs:
      - personal-files
      - network
      - home